import 'package:flutter/foundation.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import '../config/constants.dart';
import 'api_service.dart';

/// Razorpay payment gateway integration with backend order creation and verification.
///
/// Usage:
///   final service = PaymentService();
///   // Production flow — creates backend order first:
///   final orderId = await service.createOrder(
///     patientId: 'p1',
///     amount: 250000,
///     paymentType: 'invoice',
///     referenceId: 'inv-123',
///   );
///   service.openCheckout(
///     amount: 250000,
///     description: 'Hospital Bed Rental – 7 days',
///     orderId: orderId,
///     onSuccess: (response) { /* already verified on backend */ },
///     onFailure: (message) { /* show error */ },
///   );
///   // Call dispose() when done.
class PaymentService {
  late final Razorpay _razorpay;
  final ApiService _apiService;

  // Key sourced from constants — move to env config before production.
  static const _testKey = AppConstants.razorpayKey;

  VoidCallback? _onSuccessCallback;
  void Function(String)? _onFailureCallback;

  PaymentService({ApiService? apiService})
      : _apiService = apiService ?? ApiService() {
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handleSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handleError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);
  }

  /// Creates a payment order on the backend before opening checkout.
  /// Returns the Razorpay order ID to pass to [openCheckout].
  /// Returns null if the backend call fails (demo mode can proceed without it).
  Future<String?> createOrder({
    required String patientId,
    required int amount,
    required String paymentType,
    String? referenceType,
    String? referenceId,
  }) async {
    try {
      final result = await _apiService.createPaymentOrder(
        patientId: patientId,
        amount: amount,
        paymentType: paymentType,
        referenceType: referenceType,
        referenceId: referenceId,
      );
      return result['order_id'] as String?;
    } catch (e) {
      if (kDebugMode) debugPrint('Create order failed: $e');
      return null;
    }
  }

  /// Opens Razorpay checkout.
  ///
  /// [amount] is in **paise** (₹100 = 10000 paise).
  /// [orderId] should be generated by your backend via [createOrder].
  /// If [orderId] is null (demo mode), checkout opens in test mode without an order.
  void openCheckout({
    required int amount,
    required String description,
    String? orderId,
    String? prefillName,
    String? prefillPhone,
    String? prefillEmail,
    VoidCallback? onSuccess,
    void Function(String)? onFailure,
  }) {
    _onSuccessCallback = onSuccess;
    _onFailureCallback = onFailure;

    final options = <String, dynamic>{
      'key': _testKey,
      'amount': amount,
      'name': 'Housepital',
      'description': description,
      'currency': 'INR',
      'theme': {'color': '#E8820E'},
      'prefill': {
        if (prefillName != null) 'name': prefillName,
        if (prefillPhone != null) 'contact': prefillPhone,
        if (prefillEmail != null) 'email': prefillEmail,
      },
      if (orderId != null) 'order_id': orderId,
      'retry': {'enabled': true, 'max_count': 3},
      'send_sms_hash': true,
      'modal': {'confirm_close': true},
    };

    try {
      _razorpay.open(options);
    } catch (e) {
      if (kDebugMode) debugPrint('Razorpay open error: $e');
      _onFailureCallback?.call('Failed to open payment gateway');
    }
  }

  void _handleSuccess(PaymentSuccessResponse response) {
    if (kDebugMode) debugPrint('Payment success');

    // Verify payment on backend
    _verifyPaymentOnBackend(response);

    _onSuccessCallback?.call();
  }

  /// Verifies the payment signature on the backend.
  Future<void> _verifyPaymentOnBackend(PaymentSuccessResponse response) async {
    try {
      if (response.paymentId != null &&
          response.orderId != null &&
          response.signature != null) {
        await _apiService.verifyPayment(
          razorpayPaymentId: response.paymentId!,
          razorpayOrderId: response.orderId!,
          razorpaySignature: response.signature!,
        );
        if (kDebugMode) debugPrint('Payment verified on backend');
      } else {
        if (kDebugMode) debugPrint('Payment verification skipped (demo mode — missing order/signature)');
      }
    } catch (e) {
      if (kDebugMode) debugPrint('Payment verification failed: $e');
      // Don't fail the user — payment went through on Razorpay side.
      // Backend can reconcile later.
    }
  }

  void _handleError(PaymentFailureResponse response) {
    if (kDebugMode) debugPrint('Payment error: ${response.code}');
    _onFailureCallback?.call(response.message ?? 'Payment failed');
  }

  void _handleExternalWallet(ExternalWalletResponse response) {
    if (kDebugMode) debugPrint('External wallet selected');
  }

  void dispose() {
    _razorpay.clear();
  }
}
