import 'package:flutter/foundation.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import '../config/constants.dart';
import '../utils/logger.dart';
import 'api_service.dart';
import 'i_api_service.dart';

/// Razorpay payment gateway integration with backend order creation and verification.
///
/// Usage:
///   final service = PaymentService();
///   // Production flow — creates backend order first:
///   final orderId = await service.createOrder(
///     patientId: 'p1',
///     amount: 250000,
///     paymentType: 'invoice',
///     referenceId: 'inv-123',
///   );
///   service.openCheckout(
///     amount: 250000,
///     description: 'Hospital Bed Rental – 7 days',
///     orderId: orderId,
///     onSuccess: (response) { /* already verified on backend */ },
///     onFailure: (message) { /* show error */ },
///   );
///   // Call dispose() when done.
class PaymentService {
  late final Razorpay _razorpay;
  // audit batch 4 (Agent J): depend on the IApiService interface (DIP).
  // Default falls back to a concrete ApiService — keeps the existing
  // `PaymentService()` call sites working without forcing callers to wire
  // up DI plumbing, while letting tests inject a fake.
  final IApiService _apiService;

  // Key sourced from constants — move to env config before production.
  static const _testKey = AppConstants.razorpayKey;

  VoidCallback? _onSuccessCallback;
  void Function(String)? _onFailureCallback;

  PaymentService({IApiService? apiService})
      : _apiService = apiService ?? ApiService() {
    assert(
      AppConstants.razorpayKey != 'rzp_test_XXXXXXXXXX',
      'Razorpay key not configured. Set RAZORPAY_KEY env var.',
    );
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handleSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handleError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);
  }

  /// Creates a payment order on the backend before opening checkout.
  /// Returns the Razorpay order ID to pass to [openCheckout].
  /// Returns null if the backend call fails (demo mode can proceed without it).
  Future<String?> createOrder({
    required String patientId,
    required int amount,
    required String paymentType,
    String? referenceType,
    String? referenceId,
  }) async {
    try {
      final result = await _apiService.createPaymentOrder(
        patientId: patientId,
        amount: amount,
        paymentType: paymentType,
        referenceType: referenceType,
        referenceId: referenceId,
      );
      return result['order_id'] as String?;
    } catch (e) {
      Log.warn('Create order failed', error: e, tag: 'PaymentService');
      return null;
    }
  }

  /// Opens Razorpay checkout.
  ///
  /// [amount] is in **paise** (₹100 = 10000 paise).
  /// [orderId] should be generated by your backend via [createOrder].
  /// If [orderId] is null (demo mode), checkout opens in test mode without an order.
  void openCheckout({
    required int amount,
    required String description,
    String? orderId,
    String? prefillName,
    String? prefillPhone,
    String? prefillEmail,
    VoidCallback? onSuccess,
    void Function(String)? onFailure,
  }) {
    _onSuccessCallback = onSuccess;
    _onFailureCallback = onFailure;

    final options = <String, dynamic>{
      'key': _testKey,
      'amount': amount,
      'name': 'Housepital',
      'description': description,
      'currency': 'INR',
      'theme': {'color': '#E8820E'},
      'prefill': {
        'name': ?prefillName,
        'contact': ?prefillPhone,
        'email': ?prefillEmail,
      },
      'order_id': ?orderId,
      'retry': {'enabled': true, 'max_count': 3},
      'send_sms_hash': true,
      'modal': {'confirm_close': true},
    };

    try {
      _razorpay.open(options);
    } catch (e) {
      Log.warn('Razorpay open error', error: e, tag: 'PaymentService');
      _onFailureCallback?.call('Failed to open payment gateway');
    }
  }

  void _handleSuccess(PaymentSuccessResponse response) async {
    Log.debug('Payment success — verifying on backend', tag: 'PaymentService');

    // Verify payment on backend BEFORE calling success callback.
    // If verification fails, the booking must NOT be marked confirmed and
    // the cart must NOT auto-clear — callers should treat this as a failure
    // and surface the pending verification state to the user.
    final verification = await _verifyPaymentOnBackend(response);

    switch (verification) {
      case _VerificationOutcome.verified:
        _onSuccessCallback?.call();
        break;
      case _VerificationOutcome.skippedDemo:
        // Demo mode (no order_id/signature) — keep existing demo behaviour
        // so flows still complete locally without a backend.
        _onSuccessCallback?.call();
        break;
      case _VerificationOutcome.failed:
        _onFailureCallback?.call(
          "Payment under verification — we'll confirm in 24 hours",
        );
        break;
    }
  }

  /// Verifies the payment signature on the backend.
  /// Returns an outcome the caller can branch on instead of swallowing failures.
  Future<_VerificationOutcome> _verifyPaymentOnBackend(
      PaymentSuccessResponse response) async {
    if (response.paymentId == null ||
        response.orderId == null ||
        response.signature == null) {
      Log.debug('Payment verification skipped (demo mode — missing order/signature)',
          tag: 'PaymentService');
      return _VerificationOutcome.skippedDemo;
    }

    try {
      await _apiService.verifyPayment(
        razorpayPaymentId: response.paymentId!,
        razorpayOrderId: response.orderId!,
        razorpaySignature: response.signature!,
      );
      Log.debug('Payment verified on backend', tag: 'PaymentService');
      return _VerificationOutcome.verified;
    } catch (e) {
      Log.warn('Payment verification failed', error: e, tag: 'PaymentService');
      return _VerificationOutcome.failed;
    }
  }

  void _handleError(PaymentFailureResponse response) {
    Log.warn('Payment error: ${response.code}', tag: 'PaymentService');
    _onFailureCallback?.call(response.message ?? 'Payment failed');
  }

  void _handleExternalWallet(ExternalWalletResponse response) {
    Log.debug('External wallet selected', tag: 'PaymentService');
  }

  void dispose() {
    _razorpay.clear();
  }
}

/// Internal outcome of backend payment signature verification.
enum _VerificationOutcome {
  verified,
  failed,
  skippedDemo,
}
