import 'package:flutter/material.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';

/// Razorpay payment gateway integration.
///
/// Usage:
///   final service = PaymentService();
///   service.openCheckout(
///     amount: 250000, // ₹2,500 in paise
///     description: 'Hospital Bed Rental – 7 days',
///     orderId: 'order_abc123', // from backend
///     prefillName: 'Ramesh Kumar',
///     prefillPhone: '9876543210',
///     prefillEmail: 'ramesh@example.com',
///     onSuccess: (response) { /* verify on backend */ },
///     onFailure: (message) { /* show error */ },
///   );
///   // Call dispose() when done.
class PaymentService {
  late final Razorpay _razorpay;

  // TODO: Move to backend / environment config
  static const _testKey = 'rzp_test_XXXXXXXXXXXXXXX';

  VoidCallback? _onSuccessCallback;
  void Function(String)? _onFailureCallback;

  PaymentService() {
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handleSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handleError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);
  }

  /// Opens Razorpay checkout.
  ///
  /// [amount] is in **paise** (₹100 = 10000 paise).
  /// [orderId] should be generated by your backend via Razorpay Orders API.
  void openCheckout({
    required int amount,
    required String description,
    String? orderId,
    String? prefillName,
    String? prefillPhone,
    String? prefillEmail,
    VoidCallback? onSuccess,
    void Function(String)? onFailure,
  }) {
    _onSuccessCallback = onSuccess;
    _onFailureCallback = onFailure;

    final options = <String, dynamic>{
      'key': _testKey,
      'amount': amount,
      'name': 'Housepital',
      'description': description,
      'currency': 'INR',
      'theme': {'color': '#E8820E'},
      'prefill': {
        if (prefillName != null) 'name': prefillName,
        if (prefillPhone != null) 'contact': prefillPhone,
        if (prefillEmail != null) 'email': prefillEmail,
      },
      if (orderId != null) 'order_id': orderId,
      'retry': {'enabled': true, 'max_count': 3},
      'send_sms_hash': true,
      'modal': {'confirm_close': true},
    };

    try {
      _razorpay.open(options);
    } catch (e) {
      debugPrint('Razorpay error: $e');
      _onFailureCallback?.call('Failed to open payment gateway');
    }
  }

  void _handleSuccess(PaymentSuccessResponse response) {
    debugPrint('Payment success: ${response.paymentId}');
    // TODO: Verify payment on backend using:
    //   response.paymentId
    //   response.orderId
    //   response.signature
    _onSuccessCallback?.call();
  }

  void _handleError(PaymentFailureResponse response) {
    debugPrint('Payment error: ${response.code} – ${response.message}');
    _onFailureCallback?.call(response.message ?? 'Payment failed');
  }

  void _handleExternalWallet(ExternalWalletResponse response) {
    debugPrint('External wallet: ${response.walletName}');
  }

  void dispose() {
    _razorpay.clear();
  }
}
